apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-local
spec:
  repo: https://github.com/jmcglock/fleet-demo.git
  revision: main
  paths:
  - fleet-helm