apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: longhorn
  namespace: fleet-default
  labels:
    app: longhorn
    type: storage
spec:
  repo: https://github.com/jmcglock/fleet-demo
  branch: main
  paths:
  - longhorn
  targetNamespace: longhorn-system
  forceSyncGeneration: 1
  insecureBranch: false
  timeout: 300
  pollingInterval: 60