apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: recurring-snap-cleanup-per-hour
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: '0 * * * *'
  groups: [default]
  labels: {}
  name: recurring-snap-cleanup-per-hour
  task: snapshot-cleanup