apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-premium
provisioner: driver.longhorn.io
parameters:
  diskSelector: ssd
  migratable: 'true'
  numberOfReplicas: '3'
  staleReplicaTimeout: '30'
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true