apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    harvesterhci.io/cloud-init-template: user
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:cloudInit: {}
        f:metadata:
          f:labels:
            .: {}
            f:harvesterhci.io/cloud-init-template: {}
      manager: harvester
      operation: Update
  name: ubuntu-cloudinit
  namespace: default

data:
  cloudInit: |-
    #cloud-config

    package_update: true
    package_upgrade: true
    package_reboot_if_required: true

    groups:
      - admingroup: [root,sys,ubuntu]

    users:
      - name: ubuntu
        sudo: ALL=(ALL) NOPASSWD:ALL
        groups: users, admin
        home: /home/ubuntu
        shell: /bin/bash
        lock_passwd: true
        ssh_authorized_keys: 
          - <SSH_PUBLIC_KEY>

    packages:
      - wget
      - curl
      - btop

    runcmd:
      - timedatectl
      - sudo timedatectl set-ntp true
      - sudo apt-get -y autoremove
      - sudo apt-get -y autoclean
      - sudo apt-get -y clean
      - sudo systemctl daemon-reload